### ISSUE TITLE
HC_INSERT_LIBRARY Not working on Mojave with SIP without kext protection

### ISSUE THREAD

**Issue by Release-Pre-1668** [steven-michaud/HookCase#7] opened 2018-11-11 14:26 UTC
In High Sierra with SIP(without kext) was well. But Mojave's kernel say "CODE SIGNING: 430[PROCESS NAME] vm_map_protect can't have both write and exec at the same time".

**Comment by steven-michaud** [comment] 2018-11-11 14:58
I don't understand your report. All of HookCase's functionality is in its kernel extension (HookCase.kext). If you don't load it, of course it won't work. If system integrity protection (also known as "rootless mode") is turned on, you won't be able to load HookCase.kext. I just confirmed this on both HighSierra and Mojave.

**Comment by Release-Pre-1668** [comment] 2018-11-11 15:38
I'm sorry about my English level.
I already load your kext and using "kextstat" can find it. In HS with SIP(just without kext sign protection) it working. I added a LaunchDaemon plist to automatically load your's kext. But when I upgraded Mojave(with SIP) and update your's kext to version 3.0, the kernel say "CODE SIGNING: 430[PROCESS NAME] vm_map_protect can't have both write and exec at the same time".
I wanna enable SIP can be safer and I also using your's kext.Because when enable SIP DYLB_INSERT_LIBRARIES was unavailable for Apple's Binary.
Thanks!

**Comment by steven-michaud** [comment] 2018-11-11 15:45
> In HS with SIP(just without kext sign protection)

I didn't know this was possible. How do you do it? :-)

**Comment by Release-Pre-1668** [comment] 2018-11-11 15:47
Other like your's example, just disable kext sign protection("csrutil enable --without kext") In High Sierra

**Comment by steven-michaud** [comment] 2018-11-11 15:52
Interesting, and thanks! Apparently this has been true for years and I didn't know about it (https://forums.developer.apple.com/thread/17452).

Since I didn't know about it, I haven't tested with it. I'll need to do that and get back to you. It may take a while -- I'm busy with other things.

**Comment by Release-Pre-1668** [comment] 2018-11-11 15:58
I so appreciate you and your's kext, and I will waiting your good news!
Thanks!

**Comment by steven-michaud** [comment] 2018-11-17 17:32
When system integrity protection is enabled without kext protection (`csrutil enable --without kext`), I'm able to reproduce this bug on Mojave, with Safari but not with Firefox or Google Chrome. Interesting that Apple gives its own apps tighter protection.

Sometimes Safari crashes and sometimes not (I haven't been able to figure out why). But the error (in the Console app) is always something like the following:

        CODE SIGNING: 475[Safari] vm_map_protect can't have both write and exec at the same time

**Comment by steven-michaud** [comment] 2018-11-17 17:40
Apple seems to be stricter about codesigning on Mojave than on previous versions of their OS, at least with SIP protection enabled, and at least with their own apps. To deal with this I had to partially rewrite HookCase's codesigning code.

I just landed the patch, though I haven't yet tagged it with a version number. I haven't yet finished all of my testing. But it should be safe enough for you to try it, Mianmian1003. Please do so and let me know your results.

You'll need to download the latest version of the master branch. Don't do it by version number.

**Comment by steven-michaud** [comment] 2018-11-17 17:49
Oops, I forgot to mention something very important:

In order for HookCase to work on Mojave with SIP almost fully enabled (save for kext protection), you'll need to codesign your hook libraries (using `codesign -s "Your Name" hook.dylib`). For this you'll need to get a Mac Developer codesigning certificate from Apple. You'll probably need to join Apple's "Apple Developer Program". I pay $99 US per year for my membership. I think it was once possible to join without having to pay anything. I don't know if you still can. Maybe as a student?

**Comment by Release-Pre-1668** [comment] 2018-11-17 23:51
OK,I will test and tell you result. I’m Apple Developer Program member($99). 
Thanks!

**Comment by Release-Pre-1668** [comment] 2018-11-18 00:23
<img width="1330" alt="screenshot 2018-11-18 at 08 20 42" src="https://user-images.githubusercontent.com/7558132/48667145-e9d43900-eb0a-11e8-8b13-0474f24975d0.png">
OK, it work so fine.I express gratitude to you again.
Thanks!

**Comment by steven-michaud** [comment] 2018-11-18 00:51
I'm glad to hear it! And you're most welcome.

I probably won't finish my testing until sometime next week, after Thanksgiving. Only then will I bump the version number and tag it. Let me know if you see any other problems.

**Comment by Release-Pre-1668** [comment] 2018-11-18 00:54
I will waiting your’s good news. 
Thanks!

**Comment by steven-michaud** [comment] 2018-11-20 17:56
I was able to do my tests sooner than I thought. Just now I bumped HookCase's version to 3.1.

I'll close this bug, since it seems to be fixed.

**Closed as completed by steven-michaud** 2018-11-20 17:56 UTC
Labels: bug
